/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeadLetterRouteImport } from './routes/dead-letter'
import { Route as DemoLabRouteImport } from './routes/demo-lab'
import { Route as ExecutionsRouteImport } from './routes/executions'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ExecutionsIndexRouteImport } from './routes/executions.index'
import { Route as ExecutionsIdRouteImport } from './routes/executions.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadLetterRoute = DeadLetterRouteImport.update({
  id: '/dead-letter',
  path: '/dead-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLabRoute = DemoLabRouteImport.update({
  id: '/demo-lab',
  path: '/demo-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionsRoute = ExecutionsRouteImport.update({
  id: '/executions',
  path: '/executions',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionsIndexRoute = ExecutionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExecutionsRoute,
} as any)
const ExecutionsIdRoute = ExecutionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExecutionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dead-letter': typeof DeadLetterRoute
  '/demo-lab': typeof DemoLabRoute
  '/executions': typeof ExecutionsRouteWithChildren
  '/observability': typeof ObservabilityRoute
  '/settings': typeof SettingsRoute
  '/executions/$id': typeof ExecutionsIdRoute
  '/executions/': typeof ExecutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dead-letter': typeof DeadLetterRoute
  '/demo-lab': typeof DemoLabRoute
  '/observability': typeof ObservabilityRoute
  '/settings': typeof SettingsRoute
  '/executions/$id': typeof ExecutionsIdRoute
  '/executions': typeof ExecutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dead-letter': typeof DeadLetterRoute
  '/demo-lab': typeof DemoLabRoute
  '/executions': typeof ExecutionsRouteWithChildren
  '/observability': typeof ObservabilityRoute
  '/settings': typeof SettingsRoute
  '/executions/$id': typeof ExecutionsIdRoute
  '/executions/': typeof ExecutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dead-letter'
    | '/demo-lab'
    | '/executions'
    | '/observability'
    | '/settings'
    | '/executions/$id'
    | '/executions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dead-letter'
    | '/demo-lab'
    | '/observability'
    | '/settings'
    | '/executions/$id'
    | '/executions'
  id:
    | '__root__'
    | '/'
    | '/dead-letter'
    | '/demo-lab'
    | '/executions'
    | '/observability'
    | '/settings'
    | '/executions/$id'
    | '/executions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeadLetterRoute: typeof DeadLetterRoute
  DemoLabRoute: typeof DemoLabRoute
  ExecutionsRoute: typeof ExecutionsRouteWithChildren
  ObservabilityRoute: typeof ObservabilityRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dead-letter': {
      id: '/dead-letter'
      path: '/dead-letter'
      fullPath: '/dead-letter'
      preLoaderRoute: typeof DeadLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-lab': {
      id: '/demo-lab'
      path: '/demo-lab'
      fullPath: '/demo-lab'
      preLoaderRoute: typeof DemoLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executions': {
      id: '/executions'
      path: '/executions'
      fullPath: '/executions'
      preLoaderRoute: typeof ExecutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executions/': {
      id: '/executions/'
      path: '/'
      fullPath: '/executions/'
      preLoaderRoute: typeof ExecutionsIndexRouteImport
      parentRoute: typeof ExecutionsRoute
    }
    '/executions/$id': {
      id: '/executions/$id'
      path: '/$id'
      fullPath: '/executions/$id'
      preLoaderRoute: typeof ExecutionsIdRouteImport
      parentRoute: typeof ExecutionsRoute
    }
  }
}

interface ExecutionsRouteChildren {
  ExecutionsIdRoute: typeof ExecutionsIdRoute
  ExecutionsIndexRoute: typeof ExecutionsIndexRoute
}

const ExecutionsRouteChildren: ExecutionsRouteChildren = {
  ExecutionsIdRoute: ExecutionsIdRoute,
  ExecutionsIndexRoute: ExecutionsIndexRoute,
}

const ExecutionsRouteWithChildren = ExecutionsRoute._addFileChildren(
  ExecutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeadLetterRoute: DeadLetterRoute,
  DemoLabRoute: DemoLabRoute,
  ExecutionsRoute: ExecutionsRouteWithChildren,
  ObservabilityRoute: ObservabilityRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
